catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('paths/', views.PathListView.as_view(), name='paths'),
    path('path/<int:pk>', views.PathDetailView.as_view(), name='path-detail'),
    path('path/create/', views.PathCreate.as_view(), name='path-create'),
    path('path/<int:pk>/update/', views.PathUpdate.as_view(), name='path-update'),
    path('path/<int:pk>/delete/', views.PathDelete.as_view(), name='path-delete'),
    path('guaches/', views.GuacheListView.as_view(), name='guaches'),
    path('guaches/<int:pk>', views.GuacheDetailView.as_view(), name='guache-detail'),
    path('guache/create/', views.GuacheCreate.as_view(), name='guache-create'),
    path('guache/<int:pk>/update/', views.GuacheUpdate.as_view(), name='guache-update'),
    path('guaches/<int:pk>/delete/', views.GuacheDelete.as_view(), name='guache-delete'),
    path('mylearnings/', views.LearningsByUserListView.as_view(), name='my-learnings'),
    path('learnings/', views.LearningsByStaffListView.as_view(), name='learnings'),
    path('learning/<int:pk>', views.LearningDetailView.as_view(), name='learning-detail'),
    path('learning/<int:pk>/renew/', views.renew_learning_master, name='learninginstance_list_staff_user'),    
]

catalog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
import uuid

from django.conf import settings
from django.contrib.auth.models import User

from datetime import date

# Learning Tasks, The minimal unit of learning
class Task(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Knowledge task item...",
    )

    #Author of this Task
    creator = models.ForeignKey(
        'Guache',         
        on_delete=models.RESTRICT, 
        null=True,
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('task-detail', args=[str(self.id)])
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='task_name_case_insensitive_unique',
                violation_error_message="Task already exists (case insensitive match)"
            ),
        ]


# The user of the system: a warrior. Maybe act like an apprentice or a sensei
class Guache (models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)

    date_of_birth = models.DateField('birth', null=True, blank=True)
    last_visit_date = models.DateField('last in', null=True, blank=True)

    karma=models.IntegerField()

    class Meta:
        ordering=['last_name','first_name']

    def get_absolute_url(self):
        return reverse ('guache-detail', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name},{self.first_name}'


# A Planned Learning Path
# a Path contains one or more "Learning Tasks"
class Path (models.Model):
    name = models.CharField(max_length=200)
    author = models.ForeignKey(
        'Guache', 
        related_name="author_paths",
        on_delete=models.RESTRICT, 
        null=True,
    )
    apprentice = models.ManyToManyField(
        Guache, 
        related_name="learning_paths",
        help_text="Add a new Apprentice to this Learning Path",
    )

    summary = models.TextField(
        max_length=1000,
        help_text= "A Brief description of the Path",        
    )
    
    refcode = models.CharField(
        'RefCode',
        max_length=13,

    )

    task = models.ManyToManyField(
        Task, 
        help_text="Select tasks for this path",
    )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('path-detail', args=[str(self.id)])
    
    # ...get the related Learning Tasks to this Learning Path
    def display_tasks(self):
        return ', '.join(task.name for task in self.task.all()[:3])
    
    display_tasks.short_description ='Some Tasks included in this path...'
 

   
# The particular execution of a learning Path of a specific Guache
# A Guache can have one or more Learnings in execution (state defined in status)
class Learning(models.Model):

    serial = models.UUIDField(
        default=uuid.uuid4,
        help_text="Unique UUID Serial for this particular learning path",
    )

    name = models.CharField(max_length=500, null=True)

#    apprentice = models.ForeignKey('Guache', on_delete=models.RESTRICT, null=True)
#    apprentice = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    apprentice = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    path = models.ForeignKey(
        'Path',
        on_delete=models.RESTRICT,
        null=True,
    )

    last_visit = models.DateField(null=True, blank=True)

    PATH_STATUS = (
        ('w','Walking'),
        ('m','Maintenance'),
        ('d','In debt'),
        ('l','Lost'),
        ('c','Completed path'),
    )

    status = models.CharField(
        max_length=1,
        choices=PATH_STATUS,
        blank=True,
        default='w',
        help_text="Status of the Learning Path",
    )

    birth = models.DateField(null=True,blank=True)

    due_back = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['birth']
        permissions = (
            ("can_mark_completed", "Set Learning Path as Completed..."),
            ("can_mark_changed", "Set Learning as changed"),
                       )

    def __str__(self):
        return f'{self.id} ({self.path.name})'
    
    def get_absolute_url(self):
        return reverse('learning-detail', args=[str(self.id)])

    def is_overdue(self):
        """This Learning path experience is overdue?"""
        return bool(self.due_back and date.today() > self.due_back)
    

catalog/templates/catalog/guache_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Guache: {{ guache }}</h1>

{% if guache.book_set.all %}

<p>You can't delete this Guache until all their Paths have been deleted:</p>
<ul>
  {% for path in guache.path_set.all %}
    <li><a href="{% url 'path-detail' path.pk %}">{{book}}</a> ({{path.learning_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the guache?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/guache_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ guache.first_name }} {{ guache.last_name }}</h1>

  <!-- author detail link not yet defined -->
  <p><strong>Last Visit:</strong> {{ guache.last_visit_date}}</p>
  <p><strong>Karma:</strong> {{ guache.karma }}</p>

{% endblock %}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_guache or perms.catalog.delete_guache %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_guache %}
      <li><a href="{% url 'guache-update' guache.id %}">Update guache</a></li>
    {% endif %}
    {% if not guache.path_set.all and perms.catalog.delete_guache %}
      <li><a href="{% url 'guache-delete' guache.id %}">Delete Guache</a></li>
    {% endif %}
    </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/guache_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/guache_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Guache List</h1>
  {% if guache_list %}
    <ul>
      {% for guache in guache_list %}
      <li>
        <a href="{{ guache.get_absolute_url }}">{{ guache.first_name }} {{guache.last_name}}</a>        
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no guaches in the gym.</p>
  {% endif %}
{% endblock %} 

catalog/templates/catalog/learning_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ learning.name }}</h1>

  <!-- Learning Detail -->
  <p><strong>Last Visit:</strong> {{ learning.last_visit}}</p>
  <p><strong>Path:</strong> {{ learning.path }}</p>

{% endblock %}

catalog/templates/catalog/learning_renew_master.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ learning.name }}</h1>
  <p>Apprentice: {{ learning.apprentice }}</p>
  <p {% if learning.is_overdue %} class="text-danger"{% endif %} >Due date: {{ learning.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/learninginstance_list_apprentice_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Learnings</h1>

    {% if learning_list %}
    <ul>

      {% for learning in learning_list %}
      <li class="{% if learning.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'learning-detail' learning.id %}">{{ learning.name }} from {{ learning.path }}</a> ({{ learning.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no learnings...</p>
    {% endif %}
{% endblock %}
 

catalog/templates/catalog/learninginstance_list_staff_user.html
{% extends "base_generic.html" %}


{% block content %}
    <h1>System Learnings</h1>

    {% if staff_learning_list %}
    <ul>

      {% for learning in staff_learning_list %}
      <li class="{% if learning.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'learning-detail' learning.id %}">{{ learning.name }}</a> from Path: <a href="{% url 'path-detail' learning.path.id %}">{{ learning.path }}</a> ({{ learning.due_back }}) - {{learning.apprentice}} - {% if perms.catalog.can_mark_completed %}<a href="{% url 'learninginstance_list_staff_user' learning.id %}">Renew</a>{% endif %}

      </li>
      {% endfor %}
      
    </ul>

    {% else %}
      <p>There are no learnings...</p>
    {% endif %}
    {% if perms.catalog.can_mark_completed %}
      <!-- We can mark a BookInstance as returned. -->
      <!-- Perhaps add code to link to a "book return" view here. -->
      <p class="text-success">This user can mark a Learning like completed...</p>
    {% else %}
      <p class="text-danger">This user doesn't can mark a Learning like completed...</p>
    {% endif %}
    {% endblock %}
 

catalog/templates/catalog/path_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Path: {{ path }}</h1>

{% if path.book_set.all %}

<p>You can't delete this Path until all their Learnings have been deleted:</p>
<ul>
  {% for path in guache.path_set.all %}
    <li><a href="{% url 'path-detail' path.pk %}">{{Learnings}}</a> ({{path.learning_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the guache?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/path_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ path.name }}</h1>

  <p><strong>Author:</strong> <a href="">{{ path.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ path.summary }}</p>
  <p><strong>Reference Code:</strong> {{ path.refcode }}</p>
  <p><strong>Tasks:</strong> {{ path.task.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Learning Paths</h4>

    {% for lpath in path.task_set.all %}
      <hr />
      <p
        class="{% if lpath.status == 'w' %}text-success{% elif lpath.status == 'd' %}text-danger{% else %}text-warning{% endif %}">
        {{ lpath.get_status_display }}
      </p>
      {% if lpath.status != 'w' %}
        <p><strong>Learning Path not active:</strong> {{ lpath.birth }}</p>
      {% endif %}
      <p><strong>Last Visited:</strong> {{ lpath.last_visit }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ lpath.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_path or perms.catalog.delete_path %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_path %}
      <li><a href="{% url 'path-update' path.id %}">Update This Path</a></li>
    {% endif %}
    {% if perms.catalog.delete_path %}
      <li><a href="{% url 'path-delete' path.id %}">Delete this Path</a></li>
    {% endif %}
    </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/path_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/path_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Path List</h1>
  {% if path_list %}
    <ul>
      {% for path in path_list %}
      <li>
        <a href="{{ path.get_absolute_url }}">{{ path.name }}</a>
        ({{path.author}})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no Paths in the library.</p>
  {% endif %}
{% endblock %}